name: Windows MoviePilot Builder
on:
  workflow_dispatch:

jobs:
  Windows-build:
    runs-on: windows-latest
    secrets:
      - TOKEN
    steps:
    - name: Init Python 3.11.4
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.4'

    - name: Checkout
      uses: actions/checkout@v3

    - name: Install dependent packages
      run: |
        git checkout wlj0807
        dir
        # python -m pip install --upgrade pip
        # pip install -r requirements.txt
        $hash=git log -1 --pretty=%H
        $hash_version=$hash.Substring(0, 7)
        echo $hash_version
        cd ..

    - name: Download MoviePilot-Frontend
      run: |
          mkdir MoviePilot-Frontend
          cd MoviePilot-Frontend
          $response = Invoke-WebRequest -Uri 'https://api.github.com/repos/jxxghp/MoviePilot-Frontend/releases/latest' -Method GET
          # 将响应内容转换为JSON对象
          $json = $response.Content | ConvertFrom-Json
          # 提取tag_name的值
          $tagName = $json.tag_name
          # 输出tag_name的值
          echo "正在下载前端程序 $tagName..."
          # 设置URL和下载路径
          $url = "https://github.com/jxxghp/MoviePilot-Frontend/releases/download/$tagName/dist.zip"
          echo "正在下载前端程序 $url"
          # $destination = "D:\a\MoviePilot\MoviePilot\MoviePilot-Frontend\dist.zip"
          # # 使用Invoke-WebRequest下载ZIP文件
          # $response = Invoke-WebRequest -Uri $url -OutFile $destination
          # echo $response
          # echo $response.StatusCode
          # if ($response.StatusCode -eq 200) {
          # Write-Host "文件已成功下载到：$destination"
          # } else {
          # Write-Error "下载失败，状态码：$($response.StatusCode)"
          # }
          # $zipFilePath = './dist.zip'
          # Expand-Archive -Path $zipFilePath -DestinationPath dist
          dir
          cd ..

    - name: Make Python package
      run: |
          $python_dir=$(python -c "import os; print(os.path.dirname(os.__file__))")
          $python_root_dir=$python_dir.Substring(0, $python_dir.Length - 4)
          mkdir Python3.11
          cd Python3.11
#          cp -r $python_root_dir/* .
#          dir
          cd ..

#    - name: Exe Build
#      run: |
#        mkdir build
#        cd build
#        sed -i 's/old_value/new_value/g' build.iss
#        sed -i 's/1.0.9.a0ec38a/1.0.19.a0ec38a/g' 111.iss
#        iscc /DAppVersion=1.2 build.iss

    - name: Install Inno Setup Compiler
      uses: pwall2222/inno-setup-download@v0.0.4

    - name: Compile Inno Setup Script
      run: |
        Get-ChildItem -Path D:\ -Include BrazilianPortuguese.isl -File -Recurse -ErrorAction SilentlyContinue
        Get-ChildItem -Path C:\ -Include BrazilianPortuguese.isl -File -Recurse -ErrorAction SilentlyContinue
        git clone https://github.com/developer-wlj/Inno-Setup-MoviePilot.git
        cd Inno-Setup-MoviePilot
        iscc /DAppVersion=$first_version.$hash_version build.iss

    - name: Upload windows file
      uses: actions/upload-artifact@v3
      with:
        name: windows
        path: ./Windows_MoviePilot_Setup_v$first_version.$hash_version.exe

    - name: Generate Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${ first_version }.${ hash_version }
        name: v${ first_version }.${ hash_version }
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
