name: Sync Fork

on:
  schedule:
    - cron: '48 3,7,11,15,19,23 * * *'
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: repo-sync
        run: |
          curl -L -X POST -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.API_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          -s --write-out "%{http_code}\n" https://api.github.com/repos/developer-wlj/MoviePilot/merge-upstream \
          -d '{"branch":"wlj0807"}'
          curl -L -X POST -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITEE_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          -s --write-out "%{http_code}\n" https://api.github.com/repos/developer-wlj/MoviePilot-Plugins/merge-upstream \
          -d '{"branch":"main"}'
          curl -L -X POST -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITEE_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          -s --write-out "%{http_code}\n" https://api.github.com/repos/developer-wlj/MoviePilot-Resources/merge-upstream \
          -d '{"branch":"main"}'
          curl -L -X POST -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITEE_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          -s --write-out "%{http_code}\n" https://api.github.com/repos/developer-wlj/MoviePilot-Frontend/merge-upstream \
          -d '{"branch":"main"}'
          curl -L -X POST -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITEE_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          -s --write-out "%{http_code}\n" https://api.github.com/repos/developer-wlj/MoviePilot/merge-upstream \
          -d '{"branch":"docker-fix"}'

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: dev
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git remote add jxxghp https://github.com/jxxghp/MoviePilot.git
          git fetch jxxghp
          git merge jxxghp/main
          git push
