name: Build
on:
  workflow_dispatch:

jobs:
  Windows-build:
    runs-on: windows-latest
    steps:
      - name: 拉取后端代码
        uses: actions/checkout@v2
        with:
          ref: wlj0807
          repository: developer-wlj/MoviePilot
          path: 'MoviePilot'

      - name: 后端代码目录打印
        run: |
          cd MoviePilot
          pwd
          echo 111
          echo (git log -1 --pretty=format:"%h")
          echo 222
          echo (git log -2 --pretty=format:"%h")
          echo 333
          echo (git log -2 --pretty=format:"%h" | Select-Object -Skip 1)
          echo 444
          $hash_version=(git log -2 --pretty=format:"%h" | Select-Object -Skip 1)
          echo 555
          echo $hash_version
          echo 666
          echo "HASH_VERSION=$hash_version" >> $env:GITHUB_ENV
          echo 777
          echo $HASH_VERSION
          echo 888
          cat $env:GITHUB_ENV
          echo 999
