name: Build
on:
  workflow_dispatch:

jobs:
  Windows-build:
    runs-on: windows-latest
    steps:
      - name: 拉取后端代码
        uses: actions/checkout@v2
        with:
          ref: wlj0807
          repository: developer-wlj/MoviePilot
          path: 'MoviePilot'

      - name: 后端代码目录打印
        run: |
          cd MoviePilot
          pwd
          dir
          git log -2 --pretty=format:"%h"
          git log -2 --pretty=format:"%h" | Select-Object -Skip 1
          $hash_version=git log -2 --pretty=format:"%h" | Select-Object -Skip 1
          echo $hash_version
          echo "HASH_VERSION=$hash_version" >> $env:GITHUB_ENV
          echo $HASH_VERSION
          cat $env:GITHUB_ENV
